[build]
  functions = "functions"
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--production=false"

[dev]
  port = 8888
  functionsPort = 8889
  autoLaunch = false
  framework = "#static"
  targetPort = 3000
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["paynow", "@supabase/supabase-js"]
